name: solid_test
version: 0.1.0
publish_to: none
description: Flutter Solid Test Assignment.

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.14

flutter:
  uses-material-design: true
  generate: true
