name: PR Workflow
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: dart analyze
      - run: dart run dart_code_metrics:metrics analyze lib;
      - run: dart run dart_code_metrics:metrics check-unused-files lib;
      - run: dart run dart_code_metrics:metrics check-unused-l10n lib;
